'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const AR=require('../web/alert-rules.js'),HR=require('../web/research-engine.js');
const start=Date.parse('2026-09-08T14:00:00Z');
const bar=(n,v={})=>({t:start+n*900000,o:99,h:99.8,l:98.5,c:99.3,v:1000,...v});
const scenario=(v={})=>({direction:'bullish',breakoutObserved:false,hourAligned:true,volumeConfirmed:true,state:'WATCH',entry:100.1,stop:98,t1:104.3,t2:106.4,noChase:101,boundary:100,...v});
const review=(v={})=>({instrument:'etf:AMEX:SPY',symbol:'SPY',feed:'yahoo',frame:15,horizon:'INTRADAY',signalDate:'2026-09-08',sourceObservedAt:'2026-09-08T15:00:00Z',gates:[],scenarios:[scenario()],...v});
function step(p,b,r=review(),opts={}){return AR.advance(p,{review:r,bars:b,dataHash:'fixture-hash-'+b.length,now:start+b.length*900000,...opts});}
function armed(){const bars=[bar(0)],base=step(null,bars);bars.push(bar(1,{o:99.8,h:100.6,l:99.8,c:100.4}));return {...step(base.track,bars,review({scenarios:[scenario({breakoutObserved:true})]})),bars};}
test('first scan cannot replay a historical ready alert',()=>assert.equal(step(null,[bar(0)],review({scenarios:[scenario({breakoutObserved:true})]})).events.length,0));
test('new completed breakout arms frozen retest levels',()=>{const a=armed();assert.equal(a.events[0].type,'BREAKOUT_CONFIRMED');assert.equal(a.track.pending.bullish.entry,100.1);});
test('duplicate completed bar creates no repeated alert',()=>{const a=armed();assert.equal(step(a.track,a.bars).events.length,0);});
test('later retest needs context and participation and retains frozen levels',()=>{const a=armed(),b=[...a.bars,bar(2,{o:100,h:100.6,l:99.95,c:100.3})],r=review({scenarios:[scenario({entry:100.5,boundary:100.4})]}),x=step(a.track,b,r);assert.equal(x.events[0].type,'SETUP_READY_FOR_REVIEW');assert.equal(x.events[0].frozen.entry,100.1);assert.equal(x.events[0].executable,false);assert.equal(x.events[0].quantity,null);});
for(const veto of [{hourAligned:false},{volumeConfirmed:false}])test('retest waits for '+JSON.stringify(veto),()=>{const a=armed();assert.equal(step(a.track,[...a.bars,bar(2,{o:100,l:99.95,c:100.3,h:100.6})],review({scenarios:[scenario(veto)]})).events.length,0);});
test('new source bar after a pause cannot retroactively confirm',()=>{const a=armed();const x=step(a.track,[...a.bars,bar(2,{o:100,l:99.95,c:100.3,h:100.6})],review(),{resuming:true});assert.equal(x.events[0].type,'MONITOR_GAP');assert.deepEqual(x.track.pending,{});});
test('missing observed transition fails closed',()=>{const a=armed();assert.equal(step(a.track,[...a.bars,bar(2),bar(3)]).events[0].type,'MONITOR_GAP');});
test('correction withdraws confirmation without erasing audit',()=>{const a=armed();const changed=a.bars.map((b,i)=>i?{...b,c:100.2}:b);const x=step(a.track,changed);assert.equal(x.events[0].type,'CORRECTION_REVIEW_REQUIRED');assert.deepEqual(x.track.pending,{});});
test('invalidating stop takes priority over favorable intrabar high',()=>{const a=armed();assert.equal(step(a.track,[...a.bars,bar(2,{o:100,l:97.9,c:100.3,h:105})]).events[0].type,'INVALIDATED');});
test('no chase is enforced against frozen boundary',()=>{const a=armed();assert.equal(step(a.track,[...a.bars,bar(2,{o:100,l:99.95,c:101.1,h:102})]).events[0].type,'NO_CHASE');});
for(const gate of ['NON_MARKET_INPUT','STALE_REFERENCE','MANUAL_EVENT_FREEZE','CALENDAR_UNKNOWN'])test('pending setup canceled on '+gate,()=>{const a=armed();const x=step(a.track,a.bars,review({gates:[gate]}));assert.deepEqual(x.track.pending,{});assert.equal(x.events[0].type,'DATA_GATE');});
test('intraday setup does not cross a session',()=>{const a=armed();assert.deepEqual(step(a.track,[...a.bars,bar(2)],review({signalDate:'2026-09-09'})).track.pending,{});});
test('frozen setup expires after six completed retest bars',()=>{let a=armed();for(let n=2;n<=8;n++){a.bars.push(bar(n,{o:100.1,h:100.8,l:100.05,c:100.4}));a={...a,...step(a.track,a.bars,review({scenarios:[scenario({volumeConfirmed:false})]}))};};assert.equal(a.events[0].type,'EXPIRED');});
test('resuming at same completed bar can await a genuinely later bar',()=>{const a=armed(),r=step(a.track,a.bars,review(),{resuming:true});assert.ok(r.track.pending.bullish);assert.equal(step(r.track,[...a.bars,bar(2,{o:100,h:100.6,l:99.95,c:100.3})]).events[0].type,'SETUP_READY_FOR_REVIEW');});
const now=Date.parse('2026-09-08T15:00:00Z');
function chain(){const s=JSON.parse(fs.readFileSync('examples/web/demo-gex.json'));s.symbol='SPY';s.assetClass='etf';s.sessionModel='us-rth';s.instrumentId='etf:AMEX:SPY';s.dataKind='imported';s.asOf=s.spotAsOf='2026-09-08T15:00:00Z';s.options=[{id:'SPY260918C00600000',underlying:'SPY',type:'call',strike:600,expiry:'2026-09-18T20:00:00Z',expiryVerified:true,oi:1000,oiAsOf:'2026-09-07',volume:100,multiplier:100,delta:.55,gamma:.01,iv:.25,bid:5,ask:5.2,quoteAsOf:s.asOf},{id:'SPY260918C00610000',underlying:'SPY',type:'call',strike:610,expiry:'2026-09-18T20:00:00Z',expiryVerified:true,oi:1000,oiAsOf:'2026-09-07',volume:100,multiplier:100,delta:.3,gamma:.01,iv:.25,bid:2,ask:2.1,quoteAsOf:s.asOf}];return s;}
test('option screen reuses quote-side payoff and does not infer quantity',()=>{const i=HR.optionReview(chain(),{now}).ideas[0];assert.ok(i);assert.ok(Math.abs(i.entry-3.24)<1e-9);assert.ok(Math.abs(i.maxLoss-326.6)<1e-9);assert.equal(i.contracts,null);assert.equal(i.executable,false);});
test('insufficient optional premium budget gives zero',()=>assert.equal(HR.optionReview(chain(),{now,budget:100}).ideas[0].contracts,0));
test('exact underlying identity mismatch rejected',()=>{const s=chain();s.options[0].id='QQQ260918C00600000';const r=HR.optionReview(s,{now});assert.equal(r.rejected,1);assert.equal(r.ideas.length,0);});
test('date and strike linkage mismatch rejected',()=>{const s=chain();s.options[0].id='SPY260919C00601000';assert.equal(HR.optionReview(s,{now}).ideas.length,0);});
test('no chain has an actionable recovery message and no fabricated premium',()=>{const s=chain();s.options=[];const r=HR.optionReview(s,{now});assert.equal(r.ideas.length,0);assert.match(r.reason,/No option chain/);});
for(const [field,value,gate] of [['quoteAsOf',null,'QUOTE_TIME_UNKNOWN'],['quoteAsOf','2026-09-08T14:30:00Z','QUOTE_NOT_CURRENT'],['expiryVerified',false,'EXPIRY_METADATA_UNVERIFIED'],['oiAsOf','UNKNOWN','OI_DATE_UNKNOWN']])test('option quote/lifecycle gate '+gate,()=>{const s=chain();s.options[0][field]=value;const i=HR.optionReview(s,{now}).ideas[0];assert.ok(i.quoteGates.includes(gate));assert.equal(i.status,'THEORETICAL / HISTORICAL ONLY');});
test('sandbox cannot become a quoted market recommendation',()=>{const s=chain();s.dataKind='sandbox';assert.ok(HR.optionReview(s,{now}).ideas[0].quoteGates.includes('NON_MARKET_INPUT'));});
test('short spread legs need synchronized observed quotes',()=>{const s=chain();s.options[1].quoteAsOf='2026-09-08T14:59:45Z';assert.ok(HR.optionReview(s,{now}).ideas[0].quoteGates.includes('LEG_QUOTES_NOT_SYNCHRONIZED'));});
test('expired historical snapshots are never current recommendations',()=>assert.ok(HR.optionReview(chain(),{now:Date.parse('2026-09-19T15:00:00Z')}).ideas[0].quoteGates.includes('EXPIRED_CONTRACT')));
test('SPX does not inherit stock settlement or candidate rules',()=>{const s=chain();s.symbol='SPX';s.assetClass='index';assert.equal(HR.optionReview(s,{now}).ideas.length,0);});
test('0DTE is excluded by original candidate engine',()=>{const s=chain();s.options.forEach(o=>{o.expiry='2026-09-08T20:00:00Z';o.id=o.id.replace('260918','260908');});assert.equal(HR.optionReview(s,{now}).ideas.length,0);});

function ready(){const a=armed();a.bars.push(bar(2,{o:100,l:99.95,c:100.3,h:100.6}));return {...a,...step(a.track,a.bars)};}
test('ready confirmation is withdrawn on fresh-data veto',()=>{const a=ready(),x=step(a.track,a.bars,review({gates:['STALE_REFERENCE']}));assert.equal(x.track.ready,null);assert.equal(x.events[0].type,'DATA_GATE');});
test('ready confirmation withdraws on later stop breach',()=>{const a=ready(),x=step(a.track,[...a.bars,bar(3,{l:97,h:101,c:100.5})]);assert.equal(x.track.ready,null);assert.equal(x.events[0].type,'CONFIRMATION_WITHDRAWN');});
test('ready confirmation withdraws after a missed observation',()=>{const a=ready(),x=step(a.track,[...a.bars,bar(3),bar(4)]);assert.equal(x.track.ready,null);assert.equal(x.events[0].type,'MONITOR_GAP');});
test('advancing lifecycle leaves prior frozen audit untouched',()=>{const a=armed(),before=JSON.stringify(a.track);step(a.track,[...a.bars,bar(2,{o:100,l:99.95,c:100.3,h:100.6})]);assert.equal(JSON.stringify(a.track),before);});
