'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../web/symbols'),HR=require('../web/research-engine'),G=require('../web/engine'),fs=require('node:fs'),path=require('node:path');
const request={symbol:'AAPL',provider:'yahoo',interval:'5m',generation:1};
test('ticker trim and uppercase',()=>assert.equal(C.inputSymbol(' nvda '),'NVDA'));
test('exchange ticker supported',()=>assert.equal(C.inputSymbol('HKEX:700'),'HKEX:700'));
test('path rejected',()=>assert.throws(()=>C.inputSymbol('../data')));
test('URL rejected',()=>assert.throws(()=>C.inputSymbol('https://evil.test')));
test('mixed expression rejected',()=>assert.throws(()=>C.inputSymbol('AAPL+NVDA')));
test('valid latest response',()=>assert.ok(C.validResult(request,request,{symbol:'AAPL'})));
test('late old ticker response ignored',()=>assert.ok(!C.validResult(request,{...request,symbol:'NVDA'},{symbol:'AAPL'})));
test('late old generation response ignored',()=>assert.ok(!C.validResult(request,{...request,generation:2},{symbol:'AAPL'})));
test('late old provider response ignored',()=>assert.ok(!C.validResult(request,{...request,provider:'alpaca-iex'},{symbol:'AAPL'})));
test('late old interval response ignored',()=>assert.ok(!C.validResult(request,{...request,interval:'1d'},{symbol:'AAPL'})));
test('wrong symbol payload ignored',()=>assert.ok(!C.validResult(request,request,{symbol:'SPY'})));
test('IEX poll floor is 15 seconds',()=>assert.equal(C.nextDelay(15,0),15));
test('Yahoo poll floor is 60 seconds',()=>assert.equal(C.nextDelay(60,0),60));
test('backoff after two failures',()=>assert.equal(C.nextDelay(60,2),240));
test('backoff is bounded',()=>assert.equal(C.nextDelay(300,20),900));
test('off remains off',()=>assert.equal(C.nextDelay(0,2),0));
test('invalid polling rate disabled',()=>assert.equal(C.nextDelay(1,0),0));
test('no dataset means no current quote',()=>assert.equal(C.quality(null).age,null));
const now=Date.parse('2026-09-04T20:00:00Z'),s={spotAsOf:'2026-09-04T19:59:50Z',feed:'alpaca-iex',dataKind:'public-unverified'};
test('IEX coverage says polled',()=>assert.match(C.quality(s,now).label,/POLLED/));
test('old IEX last trade not live',()=>assert.match(C.quality({...s,spotAsOf:'2026-09-03T20:00:00Z'},now).label,/OLD/));
test('import cannot claim verified IEX transport',()=>assert.match(C.quality({...s,dataKind:'imported'},now).label,/SOURCE UNVERIFIED/));
test('synthetic source can never claim IEX live',()=>assert.equal(C.quality({...s,dataKind:'synthetic'},now).label,'SYNTHETIC'));
test('Yahoo refresh cannot remove delay',()=>assert.match(C.quality({...s,feed:'yahoo'},now).label,/DELAY UNKNOWN/));
test('invalid timestamp no live age',()=>assert.equal(C.quality({...s,spotAsOf:'broken'},now).label,'SOURCE TIME UNVERIFIED'));
test('future source time detected',()=>assert.equal(C.quality({...s,spotAsOf:'2099-01-01T00:00:00Z'},now).label,'SOURCE TIME UNVERIFIED'));
test('age does not use capture time',()=>assert.equal(C.quality({...s,asOf:'2099-01-01T00:00:00Z'},now).age,10));
test('native SPX recognizes nonempty chain',()=>assert.ok(C.isSPX({symbol:'SPX',options:[{}]})));
test('SPY never enters SPX workspace',()=>assert.ok(!C.isSPX({symbol:'SPY',options:[{}]})));
test('empty chain is unavailable',()=>assert.ok(!C.isSPX({symbol:'SPX',options:[]})));
const chain=JSON.parse(fs.readFileSync(path.join(__dirname,'../examples/web/spx-gex-demo.json'),'utf8'));
test('chain-only SPX computes without made-up candles',()=>{assert.equal(chain.bars.length,0);assert.ok(HR.gamma(chain).available);assert.deepEqual(HR.completed(chain,5).bars,[]);});
test('chain gamma remains capture-time estimate',()=>{const g=HR.gamma(chain);assert.ok(Number.isFinite(g.net));assert.equal(chain.dataKind,'synthetic');});
test('foreign session no invented 15m aggregation',()=>{const s=G.demo('SPY');s.symbol='VOD.L';s.sessionModel='unknown';assert.deepEqual(HR.completed(s,15).bars,[]);});
test('foreign session no US trade plan',()=>{const s=G.demo('SPY');s.symbol='VOD.L';s.sessionModel='unknown';assert.equal(HR.plans(s).action,'SESSION MODEL NOT QUALIFIED');});
test('crypto native indicators do not invent NYSE opening range',()=>{const s=G.demo('SPY');s.symbol='BTC-USD';s.sessionModel='continuous';const st=HR.stats(s,5);assert.equal(st.orh,null);assert.equal(st.vwap,null);});
test('source fixture never modified by gamma',()=>{const before=JSON.stringify(chain);HR.gamma(chain);assert.equal(JSON.stringify(chain),before);});
