'use strict';
const {test} = require('node:test');
const assert = require('node:assert/strict');
const G = require('../web/engine');
const near = (a,b,t=1e-7) => assert.ok(Math.abs(a-b)<=t, `${a} != ${b}`);
const clone = x => structuredClone(x);
function fixture() { const s=clone(G.demo('SPY'));s.bars=s.bars.slice(-120);s.options=s.options.slice(0,20);return s; }
const toy = (changes={}) => ({id:'call-100',type:'call',strike:100,expiry:'2026-09-18T20:00:00Z',expiryVerified:true,oi:100,multiplier:100,gamma:.01,iv:.2,delta:.5,bid:3,ask:3.1,volume:100,quoteAsOf:'2026-09-04T18:30:00Z',...changes});
const small = options => ({...fixture(),spot:100,options});
function chain(type='call') { return small([toy({type,delta:type==='call'?.5:-.5}),toy({id:'second',type,delta:type==='call'?.3:-.3,strike:type==='call'?105:95,bid:1,ask:1.1})]); }

test('Black–Scholes benchmark call, put and positive equal gamma',()=>{
  const c=G.bs(100,100,1,.2,.05,0,'call'),p=G.bs(100,100,1,.2,.05,0,'put');
  near(c.value,10.45058,.0001);near(p.value,5.57353,.0001);near(c.gamma,p.gamma);assert.ok(c.gamma>0);near(c.delta-p.delta,1);
});
test('put-call parity with dividend carry',()=>{const c=G.bs(105,100,.5,.3,.03,.02,'call'),p=G.bs(105,100,.5,.3,.03,.02,'put');near(c.value-p.value,105*Math.exp(-.02*.5)-100*Math.exp(-.03*.5),1e-9);});
test('Black–Scholes rejects zero/negative/nonfinite time, IV and unknown type',()=>{
 for(const args of [[100,100,0,.2],[100,100,1,0],[100,100,-1,.2],[NaN,100,1,.2],[100,100,1,.2,.04,0,'other']]) assert.throws(()=>G.bs(...args));
});
test('GEX units are dollars of delta-notional change per 1% move',()=>{const r=G.gammaExposure(small([toy()]));near(r.net,10000);near(r.gross,10000);});
test('equal calls and puts cancel only in signed-by-type convention',()=>{const d=small([toy(),toy({type:'put',id:'p',delta:-.5})]);near(G.gammaExposure(d).net,0);near(G.gammaExposure(d,{convention:'all-long'}).net,20000);near(G.gammaExposure(d,{convention:'all-short'}).net,-20000);});
test('supplied signed quantities are used instead of open interest',()=>{const r=G.gammaExposure(small([toy({position:-7})]),{convention:'signed'});near(r.net,-700);near(r.gross,10000);});
test('missing signed positions do not invent dealer exposures',()=>{const r=G.gammaExposure(small([toy()]),{convention:'signed'});assert.equal(r.rows.length,0);assert.equal(r.flip,null);assert.equal(r.missingGamma,1);});
test('missing gamma, expired rows and missing IV tracked separately',()=>{const r=G.gammaExposure(small([toy({gamma:null}),toy({strike:101,iv:null}),toy({strike:102,expiry:'2026-09-04T17:00:00Z'})]));assert.equal(r.missingGamma,1);assert.equal(r.missingIV,1);assert.equal(r.excluded,1);assert.equal(r.rows.length,1);assert.equal(r.curve.length,0);});
test('0DTE filter uses Eastern expiry date and excludes already expired options',()=>{const d=small([toy(),toy({expiry:'2026-09-04T20:00:00Z',strike:101}),toy({expiry:'2026-09-04T17:00:00Z',strike:102})]);const r=G.gammaExposure(d,{maxDays:0});assert.equal(r.rows.length,1);near(r.zeroShare,100);});
test('one-sided gamma has no fabricated zero crossing',()=>{const r=G.gammaExposure(small([toy()]),{convention:'all-long'});assert.equal(r.flip,null);assert.equal(r.flips.length,0);assert.ok(r.curve.every(p=>p.net>0));});
test('synthetic supplied and repriced gamma agree at reference spot',()=>{const r=G.gammaExposure(G.demo('SPY'));near(r.net,r.modelNetAtSpot,Math.abs(r.net)*1e-10);assert.equal(r.curve.length,81);assert.ok(r.flip>G.demo('SPY').spot*.92);});
test('EMA seed and recursive weights',()=>{assert.deepEqual(G.ema([10,20,30],3),[10,15,22.5]);assert.deepEqual(G.ema([],3),[]);});
test('RSI handles flat, rising and falling inputs',()=>{near(G.rsi(Array(20).fill(100)),50);near(G.rsi(Array.from({length:20},(_,i)=>100+i)),100);near(G.rsi(Array.from({length:20},(_,i)=>100-i)),0);assert.equal(G.rsi([1,2]),null);});
test('ATR includes an overnight price gap',()=>{const bars=Array.from({length:14},(_,i)=>({h:i===13?112:101,l:i===13?110:99,c:i===13?111:100}));near(G.atr(bars),38/14);});
test('VWAP resets each session; zero-volume and daily bars expose no VWAP',()=>{const b=fixture().bars;const i=G.indicators(b,5);const lastSession=b.at(-1).session,day=b.filter(x=>x.session===lastSession);near(i.vwap,day.reduce((s,x)=>s+(x.h+x.l+x.c)/3*x.v,0)/day.reduce((s,x)=>s+x.v,0));assert.equal(G.indicators(b.map(x=>({...x,v:0}))).vwap,null);assert.equal(G.indicators(b,1440).vwap,null);});
test('aggregation keeps sessions separate and preserves OHLCV',()=>{const b=G.demo('SPY').bars.slice(-60,-54);const a=G.aggregate(b,15);assert.equal(a.length,2);near(a[0].o,b[0].o);near(a[0].c,b[2].c);near(a[0].h,Math.max(...b.slice(0,3).map(x=>x.h)));near(a[0].v,b.slice(0,3).reduce((s,x)=>s+x.v,0));assert.throws(()=>G.aggregate(b,1,5));});
test('DST-aware session ends resolve winter and summer',()=>{assert.equal(new Date(G.easternSessionEnd('2026-09-04')).toISOString(),'2026-09-04T20:00:00.000Z');assert.equal(new Date(G.easternSessionEnd('2026-01-05')).toISOString(),'2026-01-05T21:00:00.000Z');assert.equal(new Date(G.easternSessionEnd('2026-09-04',true)).toISOString(),'2026-09-04T21:00:00.000Z');});
test('closed bar filtering excludes current partial and daily session',()=>{const d=fixture();d.asOf='2026-09-04T18:29:00Z';assert.ok(G.closedBars(d,5).at(-1).t+300000<=Date.parse(d.asOf));assert.equal(G.closedBars(d,1440).at(-1).session,'2026-09-03');assert.deepEqual(G.closedBars(d,1),[]);});
test('futures overnight daily bucket is not closed before next session end',()=>{const d=fixture();d.symbol='ES';d.asOf='2026-09-03T23:30:00Z';d.bars=Array.from({length:12},(_,i)=>({t:Date.parse('2026-09-03T22:00:00Z')+i*300000,o:5000,h:5002,l:4999,c:5001,v:100,session:'2026-09-04'}));assert.equal(G.closedBars(d,1440).length,0);assert.equal(G.closedBars(d,60).length,1);});
test('futures sizing includes two sides of fees and slippage',()=>{const r=G.riskSize({equity:25000,riskPct:.5,entry:5000,stop:4990,symbol:'MES',fee:1,slippageTicks:1});near(r.budget,125);near(r.perContract,54.5);assert.equal(r.contracts,2);near(r.total,109);});
test('futures tick/point values and zero-size risk cap',()=>{for(const [s,p] of [['ES',50],['MES',5],['NQ',20],['MNQ',2]]){const r=G.riskSize({equity:100,riskPct:.5,entry:5000,stop:4990,symbol:s});near(r.pointValue,p);near(r.tickValue,p*.25);assert.equal(r.contracts,0);}});
test('risk rejects zero equity, identical stop, unsupported symbol and excessive percentage',()=>{const a={equity:25000,riskPct:.5,entry:5000,stop:4990,symbol:'ES'};for(const x of [{equity:0},{entry:4990},{symbol:'SPY'},{riskPct:6},{fee:-1}])assert.throws(()=>G.riskSize({...a,...x}));});
test('call vertical max loss, max gain and breakeven agree with payoff',()=>{const p=G.optionPlan(chain(),{equity:100000,riskPct:1});assert.ok(p.ok);near(p.entry,2.14);near(p.maxLoss,215.3);near(p.maxGain,284.7);near(p.breakeven,102.153);near(G.optionPayoff(p,90),-p.maxLoss);near(G.optionPayoff(p,110),p.maxGain);near(G.optionPayoff(p,p.breakeven),0);assert.equal(p.contracts,4);});
test('bear put vertical has mirrored payoff and valid strikes',()=>{const p=G.optionPlan(chain('put'),{direction:'bearish'});assert.ok(p.ok);assert.ok(p.sell.strike<p.buy.strike);near(G.optionPayoff(p,110),-p.maxLoss);near(G.optionPayoff(p,90),p.maxGain);near(G.optionPayoff(p,p.breakeven),0);});
test('long call is uncapped; long put maximum occurs at zero underlying',()=>{const c=G.optionPlan(chain(),{style:'single'}),p=G.optionPlan(chain('put'),{direction:'bearish',style:'single'});assert.equal(c.maxGain,Infinity);near(G.optionPayoff(p,0),p.maxGain);assert.equal(c.contracts,0);});
test('unverified expiry, stale quotes, low OI and crossed/illiquid spreads rejected',()=>{for(const change of [{expiryVerified:false},{quoteAsOf:'2026-09-04T18:00:00Z'},{oi:0},{volume:0},{ask:6},{delta:null},{delta:-.5},{bid:4,ask:3}]){const d=chain();d.options=d.options.map(o=>({...o,...change}));assert.equal(G.optionPlan(d).ok,false,JSON.stringify(change));}});
test('options do not substitute 0DTE or trade neutral direction',()=>{const d=chain();d.options=d.options.map(o=>({...o,expiry:'2026-09-04T20:00:00Z'}));assert.equal(G.optionPlan(d).ok,false);assert.equal(G.optionPlan(chain(),{direction:'neutral'}).ok,false);assert.throws(()=>G.optionPlan(chain(),{direction:'sideways'}));});
test('costs cannot consume entire possible spread profit',()=>{assert.equal(G.optionPlan(chain(),{fee:200}).ok,false);});
test('snapshot import validates and never accepts a claimed live/demo mode',()=>{const d=fixture();d.mode='live';const v=G.validateSnapshot(d);assert.equal(v.mode,'imported');assert.ok(v.spotAsOf);assert.equal(v.bars.length,120);});
test('snapshot rejects date-only timestamps, duplicate options and bad OHLC',()=>{for(const mut of [d=>d.asOf='2026-09-04',d=>d.options[0].expiry='2026-09-18',d=>d.options.push(clone(d.options[0])),d=>d.bars[0].h=1,d=>d.bars[0].session='hello',d=>d.bars[1].t=d.bars[0].t,d=>d.options[0].quoteAsOf='2026-09-05T18:30:00Z',d=>d.bars[0].v=-1]){const d=fixture();mut(d);assert.throws(()=>G.validateSnapshot(d));}});
test('event freeze cannot create an executable trade',()=>{const d=G.demo('SPY'),s=G.setup(d,G.closedBars(d,5),{eventFreeze:true});assert.equal(s.state,'EVENT FREEZE');assert.equal(s.paperOnly,true);assert.ok(s.gates.some(x=>x.includes('Manual event')));});
test('fresh retrieval time does not hide stale underlying price',()=>{const d=fixture();d.mode='imported';d.asOf=new Date().toISOString();d.spotAsOf='2026-01-01T20:00:00Z';const s=G.setup(d,d.bars);assert.ok(s.gates.some(x=>x.includes('Reference price is stale')));});
test('zero ATR and short histories cannot produce entries',()=>{const d=fixture();assert.equal(G.setup(d,d.bars.slice(0,10)).state,'INSUFFICIENT DATA');const b=d.bars.map(x=>({...x,o:100,h:100,l:100,c:100}));assert.equal(G.setup(d,b).state,'INSUFFICIENT DATA');});
test('demo is reproducible, labeled and has no native futures options',()=>{assert.deepEqual(G.demo('SPY'),G.demo('SPY'));assert.equal(G.demo('ES').options.length,0);assert.equal(G.demo('SPY').mode,'demo');assert.ok(G.demo('SPY').warnings.some(x=>/synthetic/i.test(x)));});
