'use strict';
const test=require('node:test'), assert=require('node:assert/strict'), HR=require('../web/research-engine'),G=require('../web/engine');
const clone=x=>JSON.parse(JSON.stringify(x));
function sample(){const s=clone(G.demo('SPY'));s.dataKind='synthetic';s.spotAsOf=s.asOf;return s;}
const risk={symbol:'MES',side:'long',equity:100000,riskPct:.25,entry:6000,stop:5990,fee:1.25,slippageTicks:2,margin:null};
test('missing chain is unavailable, not zero evidence',()=>{const s=sample();s.options=[];assert.equal(HR.gamma(s).available,false);assert.equal(HR.quality(s).executable,false);});
test('unknown OI is excluded and counted',()=>{const s=sample();s.options[0].oi=null;const g=HR.gamma(s);assert.equal(g.missingOI,1);assert.ok(!g.normalizedOptions.some(x=>x.id===s.options[0].id));});
test('missing equity gamma can be modeled from supplied IV',()=>{const s=sample();s.options.forEach(o=>o.gamma=null);assert.ok(HR.gamma(s).modeled>0);});
test('gamma calculation never changes source rows',()=>{const s=sample(),before=JSON.stringify(s);HR.gamma(s);assert.equal(JSON.stringify(s),before);});
test('native futures missing gamma is not guessed using equity BS',()=>{const s=sample();s.symbol='MES';s.options.forEach(o=>o.gamma=null);assert.equal(HR.gamma(s).available,false);});
test('native futures supplied gamma has no fabricated equity-style flip',()=>{const s=sample();s.symbol='MES';const g=HR.gamma(s);assert.equal(g.flip,null);assert.deepEqual(g.curve,[]);assert.equal(g.modeled,0);});
test('no finer candles from daily input',()=>{const s=sample();s.barMinutes=1440;assert.deepEqual(HR.completed(s,15).bars,[]);assert.equal(HR.stats(s,15).direction,'neutral');});
test('incomplete base candle is excluded',()=>{const s=sample();const last=s.bars.at(-1);s.asOf=new Date(last.t+60000).toISOString();assert.ok(HR.completed(s,5).bars.at(-1).t<last.t);});
test('gapped 15 minute bucket is rejected',()=>{const s=sample();const t=Date.parse('2026-09-04T13:30:00Z');s.bars=[0,2].map(i=>({t:t+i*300000,o:100,h:101,l:99,c:100,v:10}));s.asOf='2026-09-04T13:45:00Z';assert.equal(HR.completed(s,15).bars.length,0);});
test('complete 15 minute bucket passes at close, not earlier',()=>{const s=sample();const t=Date.parse('2026-09-04T13:30:00Z');s.bars=[0,1,2].map(i=>({t:t+i*300000,o:100,h:101,l:99,c:100,v:10}));s.asOf='2026-09-04T13:45:00Z';assert.equal(HR.completed(s,15).bars.length,1);s.asOf='2026-09-04T13:44:59Z';assert.equal(HR.completed(s,15).bars.length,0);});
test('event freeze suppresses scenario generation',()=>{const p=HR.plans(sample(),{eventFreeze:true});assert.equal(p.action,'EVENT FREEZE');assert.deepEqual(p.scenarios,[]);});
test('planning never claims executable signal',()=>{const p=HR.plans(sample());assert.equal(p.executable,false);assert.ok(p.scenarios.every(x=>x.executable===false));});
test('prior hourly context ends before latest 15m trigger starts',()=>{const s=sample(),p=HR.plans(s),last=p.stats.series.at(-1);assert.ok(p.hour.series.every(b=>b.t+3600000<=last.t));});
test('flat prices produce insufficient risk structure',()=>{const s=sample();s.bars=s.bars.map(b=>({...b,o:100,h:100,l:100,c:100}));assert.equal(HR.plans(s).action,'INSUFFICIENT DATA');});
test('call debit spread arithmetic including fees',()=>{const p=HR.manualOption({type:'call',buyStrike:100,sellStrike:105,debit:2,fees:2.6,equity:100000,riskPct:.25});assert.equal(p.maxLoss,202.6);assert.equal(p.maxGain,297.4);assert.equal(p.breakeven,102.026);assert.equal(p.contracts,1);assert.equal(G.optionPayoff(p,105),297.4);});
test('put debit spread arithmetic',()=>{const p=HR.manualOption({type:'put',buyStrike:100,sellStrike:95,debit:2,fees:2.6,equity:100000,riskPct:.25});assert.equal(p.breakeven,97.974);assert.equal(G.optionPayoff(p,90),297.4);});
test('long call max gain uncapped; full premium risk included',()=>{const p=HR.manualOption({type:'call',buyStrike:100,debit:2,fees:2.6,equity:100000,riskPct:.25});assert.equal(p.maxGain,Infinity);assert.equal(G.optionPayoff(p,90),-202.6);});
test('spread exceeding risk budget remains zero',()=>{const p=HR.manualOption({type:'call',buyStrike:100,sellStrike:110,debit:6,fees:2.6,equity:1000,riskPct:1});assert.equal(p.contracts,0);});
test('invalid spread debit rejected',()=>assert.throws(()=>HR.manualOption({type:'call',buyStrike:100,sellStrike:105,debit:5,equity:100000,riskPct:.25})));
test('inverted call strike rejected',()=>assert.throws(()=>HR.manualOption({type:'call',buyStrike:100,sellStrike:95,debit:2,equity:100000,riskPct:.25})));
test('risk requires valid direction',()=>assert.throws(()=>HR.futureRisk({...risk,side:'banana'})));
test('MES risk includes two sides of costs',()=>{const r=HR.futureRisk(risk);assert.equal(r.stopRisk,50);assert.equal(r.costs,7.5);assert.equal(r.perContract,57.5);assert.equal(r.riskOnlyContracts,4);});
test('unknown margin blocks final futures size',()=>{const r=HR.futureRisk(risk);assert.equal(r.contracts,null);assert.equal(r.executable,false);});
test('user margin can reduce but never enlarge risk size',()=>{assert.equal(HR.futureRisk({...risk,margin:60000}).contracts,1);assert.equal(HR.futureRisk({...risk,margin:1}).contracts,4);});
test('off tick futures price rejected',()=>assert.throws(()=>HR.futureRisk({...risk,entry:6000.1})));
test('wrong stop side rejected',()=>assert.throws(()=>HR.futureRisk({...risk,stop:6010})));
test('NQ correct multiplier changes risk size',()=>{const r=HR.futureRisk({...risk,symbol:'NQ',margin:10000});assert.equal(r.stopRisk,200);assert.equal(r.costs,22.5);assert.equal(r.contracts,1);});
test('zero equity rejected',()=>assert.throws(()=>HR.futureRisk({...risk,equity:0})));
test('chain ideas all remain nonexecutable',()=>{const a=HR.optionIdeas(sample()).ideas;assert.ok(a.every(x=>x.executable===false));});
test('no 0DTE recommendations',()=>{const s=sample();s.options.forEach(o=>o.expiry=s.asOf);assert.equal(HR.optionIdeas(s).ideas.length,0);});
test('empty chain produces no invented contracts',()=>{const s=sample();s.options=[];assert.equal(HR.optionIdeas(s).ideas.length,0);});
test('continuous futures source is explicitly flagged',()=>{const s=sample();s.continuous=true;assert.ok(HR.quality(s).reasons.some(x=>x.includes('Continuous')));});
test('gamma positioning conventions preserve signs',()=>{const s=sample();assert.ok(HR.gamma(s,{convention:'all-long'}).net>=0);assert.ok(HR.gamma(s,{convention:'all-short'}).net<=0);});
test('integrated KX context matches shared Python vector and has no entry authority',()=>{const v=require('./fixtures/kx-context-vector.json'),s=sample();s.barMinutes=5;s.bars=v.bars;s.asOf=new Date(v.bars.at(-1).t+300000).toISOString();s.spot=s.bars.at(-1).c;s.spotAsOf=s.asOf;const r=HR.integratedContext(s,5),e=v.expected;assert.equal(r.structure,e.structure);for(const side of ['long','short']){for(const key of ['momentum3Atr','momentum10Atr','rangeAtr','bodyFraction','directionalCloseLocation'])assert.ok(Math.abs(r[side][key]-e[side][key])<1e-10,key);assert.deepEqual(r[side].evidence,e[side].evidence);}assert.equal(r.entryAuthority,false);assert.equal(r.sameBarEntryAllowed,false);assert.equal(r.qualification,'KX_BLOCKED_9_GATES');});
test('KX pivots are exposed only on their later confirmation bar',()=>{const bars=[1,2,5,2,1].map((h,i)=>({t:i,o:1,h,l:.5,c:1,v:1}));const p=HR.confirmedPivots(bars,2);assert.equal(p.highs.length,1);assert.equal(p.highs[0].pivotIndex,2);assert.equal(p.highs[0].confirmedIndex,4);});
