const test=require('node:test'),assert=require('node:assert/strict'),F=require('../web/futures-tools'),HR=require('../web/research-engine'),M=require('../web/monitor-tools'),G=require('../web/engine');
const t=Date.parse('2026-09-09T22:00:00Z');
function fixture(){return {symbol:'MESU6',instrumentId:'CME:MESU6',assetClass:'future',future:{root:'MES',exact:true,expiryAt:'2026-09-18T13:30:00Z',pointValue:5,tickSize:.25,tickValue:1.25},futureSessions:[{date:'2026-09-10',known:true,completeSessionKnown:true,open:t,close:t+23*3600000,segments:[[t,t+22.25*3600000],[t+22.5*3600000,t+23*3600000]]}],asOf:new Date(t+180*300000).toISOString(),spotAsOf:new Date(t+180*300000).toISOString(),spot:6090,feed:'imported',dataKind:'imported',sessionModel:'cme-equity-index',barMinutes:5,bars:Array.from({length:180},(_,i)=>({t:t+i*300000,o:6000+i*.5,h:6001+i*.5,l:5999+i*.5,c:6000.5+i*.5,v:100+i%10})),options:[]};}
test('CME aggregation anchors overnight bars and excludes forming buckets',()=>{const s=fixture();assert.equal(HR.completed(s,15).bars.length,60);s.asOf=new Date(t+179*300000).toISOString();assert.equal(HR.completed(s,15).bars.length,59);assert.equal(HR.completed(s,15).bars[0].session,'2026-09-10');});
test('missing, corrected and unfinished futures candles do not complete buckets',()=>{const s=fixture();s.bars.splice(1,1);assert.equal(HR.completed(s,15).bars.length,59);s.bars.at(-1).finalized=false;assert.equal(HR.completed(s,15).bars.length,58);});
test('unknown holiday session produces no invented candles',()=>{const s=fixture();s.futureSessions[0].known=false;assert.equal(HR.completed(s,15).bars.length,0);});
test('partial final period is explicit; daily requires every observed trading minute',()=>{const s=fixture(),w=s.futureSessions[0];s.bars=[];for(const [a,z] of w.segments)for(let at=a;at<z;at+=300000)s.bars.push({t:at,o:1,h:2,l:.5,c:1,v:10});s.asOf=new Date(w.close).toISOString();assert.ok(HR.completed(s,60).bars.some(b=>b.partialPeriod));assert.equal(HR.completed(s,1440).bars.length,1);s.bars.pop();assert.equal(HR.completed(s,1440).bars.length,0);});
test('exact-contract entries and stops round to CME ticks with per-contract costs',()=>{const s=fixture(),r=M.review(s,{now:Date.parse(s.asOf)});assert.equal(r.scenarios.length,2);for(const x of r.scenarios)for(const k of ['entry','stop','t1','t2','noChase'])assert.equal(x[k]*4,Math.round(x[k]*4));assert.equal(r.futuresCosts.roundTripUsd,5);assert.equal(r.scenarios[0].riskPerContract,Math.abs(r.scenarios[0].entry-r.scenarios[0].stop)*5+5);assert.equal(r.quantity,null);assert.ok(r.gates.includes('FUTURES_ENTRY_TIMING_UNVERIFIED'));});
test('continuous futures and expired contracts veto current timing',()=>{const s=fixture();s.future.exact=false;let r=M.review(s,{now:Date.parse(s.asOf)});assert.ok(r.gates.includes('CONTINUOUS_REFERENCE_ONLY'));s.future.expiryAt='2026-01-01T00:00:00Z';r=M.review(s,{now:Date.parse(s.asOf)});assert.ok(r.gates.includes('CONTRACT_EXPIRED'));});
test('roll boundaries and different feeds cannot pair price references',()=>{const a=fixture();a.barMinutes=1440;const b={...fixture(),instrumentId:'CME:MESZ6',spot:9000,spotAsOf:'2026-09-11T00:00:00Z'};assert.equal(M.pairReference(a,b),a);});
test('card uses frozen confirmation levels and recomputes net RR',()=>{const r=M.review(fixture(),{now:t+180*300000});r.gates=[];const p={...r.scenarios[0],entry:6000,stop:5990,t1:6020,t2:6030,noChase:6001};const c=M.card(r,{ready:p},true);assert.equal(c.scenario.entry,6000);assert.equal(c.scenario.netT1.ratio,19/11);assert.equal(c.priority,0);assert.notEqual(M.card(r,{ready:p},false).priority,0);});
test('conflicting aligned scenarios return WAIT and empty cards are not manufactured',()=>{const r=M.review(fixture(),{now:t+180*300000});r.gates=[];r.scenarios.forEach(x=>{x.hourAligned=true;x.state='WATCH';});assert.equal(M.card(r,null).direction,'WAIT');assert.deepEqual(M.rankCards([]),[]);});
test('ranking uses confirmation, rule score, then net RR',()=>{const cards=[{priority:1,score:99,netRR:2},{priority:0,score:1,netRR:1},{priority:1,score:99,netRR:3}];assert.deepEqual(M.rankCards(cards),[cards[1],cards[2],cards[0]]);});
function chain(){const s=G.demo('SPX');s.symbol='SPX';s.options=s.options.slice(0,4).map(o=>({...o,underlying:'SPX',root:'SPXW',multiplier:100,lifecycleVerified:true,expiryVerified:true,modelExpiryAt:o.expiry,payoffFixingAt:o.expiry}));s.dataKind='synthetic';s.oiAsOf='original-oi-date';return s;}
test('repricing retains original chain provenance, synthetic kind and immutable source',()=>{const s=chain(),before=JSON.stringify(s),at=new Date(Date.parse(s.asOf)+3600000).toISOString(),r=HR.repriceGamma(s,{spot:s.spot+10,spotAsOf:at,source:'TEST SPX observation',now:Date.parse(at)});assert.ok(r.available,r.reason);assert.equal(JSON.stringify(s),before);assert.equal(r.snapshot.dataKind,'synthetic');assert.equal(r.provenance.chainCapturedAt,s.asOf);assert.equal(r.snapshot.oiAsOf,s.oiAsOf);const o=r.snapshot.options[0],years=(Date.parse(o.modelExpiryAt)-Date.parse(at))/(365*86400000);assert.equal(o.gamma,G.bs(s.spot+10,o.strike,years,o.iv,s.rate??.04,s.dividend??0,o.type).gamma);});
test('repricing rejects unqualified lifecycle, missing OI, missing IV and proxy identity',()=>{for(const field of ['lifecycleVerified','oi','iv','root']){const s=chain();s.dataKind='imported';s.options[0][field]=field==='lifecycleVerified'?false:field==='root'?'SPY':null;s.options[0].quoteAsOf=null;const at=new Date(Date.parse(s.asOf)+3600000).toISOString();assert.equal(HR.repriceGamma(s,{spot:s.spot,spotAsOf:at,source:'TEST',now:Date.parse(at)}).available,false,field);}});
test('repricing rejects old or future price and expired chain',()=>{const s=chain();for(const at of [s.asOf,new Date(Date.parse(s.asOf)+100000).toISOString()])assert.equal(HR.repriceGamma(s,{spot:s.spot,spotAsOf:at,source:'TEST',now:Date.parse(s.asOf)}).available,false);const at='2099-01-01T00:00:00Z';assert.equal(HR.repriceGamma(s,{spot:s.spot,spotAsOf:at,source:'TEST',now:Date.parse(at)}).available,false);});
