/* Free-first chart workspace. It intentionally does not read TradingView prices. */
'use strict';
const savedChart=(()=>{try{return JSON.parse(localStorage.getItem('hub.chart.v4')||'{}');}catch{return {};}})();
const C={symbol:savedChart.symbol||'AAPL',info:null,interval:savedChart.interval||'15m',provider:savedChart.provider||'yahoo',mode:'local',timezone:savedChart.timezone||'Europe/London',recent:Array.isArray(savedChart.recent)?savedChart.recent.slice(0,12):['AAPL','NVDA','TSLA','SPX','ES','NQ'],snapshot:null,widgetConsent:false,auto:0,failures:0,generation:0,busy:false,lastAttempt:null,lastSuccess:null,nextAt:null,timer:null,error:'',quoteMessage:'',initialized:false,stream:null,streamClient:null,streamSequence:0,streamTimer:null};
function saveChartPrefs(){localStorage.setItem('hub.chart.v4',JSON.stringify({symbol:C.symbol,interval:C.interval,provider:C.provider,timezone:C.timezone,recent:C.recent}));}
function chartMoney(v,s=C.snapshot){return Number.isFinite(v)?num(v)+' '+E(s?.currency||'price units'):'—';}
function chartDataHTML(){
 const s=C.snapshot,q=ChartTools.quality(s),info=C.info;
 if(!s)return `<div class="notice info"><strong>Choose your own symbol, then click Fetch data.</strong> The old SPY dataset is not substituted here. Your chart request is <strong>${E(C.symbol)}</strong>. ${info&&!info.yahoo?'This exchange symbol has no local Yahoo mapping; use Online chart or import a provider ticker.':''}</div>`+empty('No local observations for '+C.symbol,'Fetch free public history, use your optional IEX keys, or load an existing dataset. The online chart can be used separately without a data API key.');
 const st=HR.stats(s,s.barMinutes);charts.set('selected-price-chart',{type:'candles',bars:st.series,minutes:s.barMinutes});
 return `<div class="notice ${s.dataKind==='synthetic'||s.dataKind==='sandbox'?'':'info'}"><strong>${E(q.label)}</strong> · ${E(s.symbol)} · last observation <span data-chart-age>${E(ChartTools.ageText(q.age))}</span> ago. ${E(q.detail)}</div>`+
 `<div class="metrics">${metric('REFERENCE / LAST TRADE',chartMoney(s.spot,s),'Observed '+dt(s.spotAsOf))}${metric('COMPLETED-BAR TREND',st.insufficient?'Insufficient':E(st.direction.toUpperCase()),`${st.series.length} complete ${s.barMinutes===1440?'daily':s.barMinutes+'m'} bars`,'small')}${metric('RSI14 / ATR14',st.insufficient?'—':num(st.rsi,1)+' / '+num(st.atr),s.feed==='alpaca-iex'?'IEX-only volume; not consolidated':'No current candle in signal calculations','small')}${metric('TECHNICAL RULE SCORE',st.insufficient?'—':num(st.score.score,0)+' / 100','Not a probability or validated return forecast','small')}</div>`+
 `<div class="observation-strip"><span><b>DATA SYMBOL</b> ${E(s.symbol)}</span><span><b>OBSERVED</b> ${E(dt(s.spotAsOf))}</span><span><b>CAPTURED</b> ${E(dt(s.asOf))}</span><span><b>CURRENCY</b> ${E(s.currency||'UNKNOWN')}</span></div>`+
 (C.mode==='local'?panel(s.symbol+' · local research chart','Completed bars; latest trade/reference may be newer than the last complete candle',`<div id="price-readout" class="chart-readout">Hover over candles or focus the chart and use ←/→ for OHLCV.</div>${chartHTML('selected-price-chart','tall')}<div class="chart-legend"><span><i class="legend-mark gold"></i>EMA20</span><span><i class="legend-mark blue"></i>EMA50</span><span>Volume: source venue(s) only · session metadata retained</span></div>`,`<div class="row">${button('−','chart-zoom-out','small','aria-label="Show more candles"')}${button('+','chart-zoom-in','small','aria-label="Show fewer candles"')}${button('← Older','chart-pan-left','small')}${button('Newer →','chart-pan-right','small')}${button('Reset','chart-reset','small')}</div>`,E(st.note||'No additional candles invented or forward-filled; dataset provenance is shown above.')+' The chart is priced in the source currency; not every venue has volume.'):'')+
 `<div class="row wide-space">${button('Save snapshot & open analysis →','chart-analyse','primary')}${button('Export this snapshot ↓','chart-export')}${button('Save observation to journal','chart-note')}</div>`+
 `<details class="details-card"><summary>Source, coverage and calculation limitations</summary><p>${E(s.source)}</p><p>Session model: ${E(s.sessionModel||'us-rth')} · provider timezone: ${E(s.exchangeTimezone||'UNKNOWN')} · adjustments: ${E(s.adjustment)}</p><p>${(s.warnings||[]).map(E).join('<br>')}</p><p>The displayed provider chart, local price model and native SPX chain are distinct datasets. No values are extracted from the TradingView iframe.</p></details>`;
}
function renderCharts(){
 const tv=C.info?.tradingview||C.symbol,frame={'1m':'1','5m':'5','15m':'15','1h':'60','4h':'240','1d':'D','1w':'W'}[C.interval]||'15',favorite=(S.prefs?.favorites||[]).includes(C.symbol);
 const available=S.snapshots.filter(s=>s.symbol===C.symbol&&s.barCount>=2);
 return pageHeading('FREE-FIRST / USER-SELECTED SYMBOLS','Your market, your chart','Choose a ticker instead of a fixed SPY screen. SPX gamma stays in its own workspace.',`${button(favorite?'★ Favorite':'☆ Add favorite','chart-favorite',favorite?'warn':'')}<a href="#gex" class="button">SPX GEX →</a>`)+
 `<div class="panel chart-command"><form id="chart-symbol-form"><div class="symbol-entry"><label for="chart-symbol">SYMBOL / COMPANY ALIAS</label><input id="chart-symbol" name="symbol" value="${E(C.symbol)}" placeholder="NVDA, AAPL, AMD, SPX, ES…" maxlength="40" autocomplete="off" spellcheck="false" required list="chart-symbols"><datalist id="chart-symbols">${['AAPL','NVDA','TSLA','MSFT','AMD','GOOGL','MU','PLTR','V','MCD','QQQ','SPY','SPX','ES','NQ','NYSE:BRK.B','LSE:VOD','HKEX:700','BTC-USD'].map(s=>`<option value="${s}"></option>`).join('')}</datalist></div><button type="submit" class="button primary">Open symbol →</button><div><label for="chart-interval">DATA INTERVAL</label><select id="chart-interval">${[['1m','1 minute'],['5m','5 minutes'],['15m','15 minutes'],['1h','1 hour'],['4h','4 hours · aggregated'],['1d','Daily'],['1w','Weekly']].map(([v,k])=>`<option value="${v}" ${C.interval===v?'selected':''}>${k}</option>`).join('')}</select></div></form>${(S.prefs?.favorites||[]).length?`<div class="symbol-chips" aria-label="Favorite symbols">${S.prefs.favorites.map(s=>`<button data-action="chart-symbol" data-symbol="${E(s)}" class="chip ${s===C.symbol?'selected':''}">★ ${E(s)}</button>`).join('')}</div>`:''}<div class="symbol-chips" aria-label="Recent symbols">${C.recent.map(s=>`<button data-action="chart-symbol" data-symbol="${E(s)}" class="chip ${s===C.symbol?'selected':''}">${E(s)}</button>`).join('')}</div><div class="mapping-line"><strong>${E(C.info?.assetClass||'unknown')}</strong> · ${E(C.info?.exchange||'unknown exchange')} · ${E(C.info?.currency||'unknown currency')} · ${E(C.info?.exchangeTimezone||'unknown timezone')} · Online: <strong>${E(tv)}</strong> · Yahoo: <strong>${E(C.info?.yahoo||'Not mapped')}</strong> · GEX: <strong>SPX only</strong></div></div>`+
 `<div class="chart-control-row"><div class="tabs switcher"><button class="tab ${C.mode==='local'?'active':''}" data-action="chart-local">Local chart + analysis</button><button class="tab ${C.mode==='online'?'active':''}" data-action="chart-online">Online provider chart</button></div><div class="row"><a class="button small" href="https://www.tradingview.com/chart/?symbol=${encodeURIComponent(tv)}" target="_blank" rel="noopener noreferrer">Open on TradingView ↗</a><select id="chart-timezone" aria-label="Online chart timezone">${['Europe/London','America/New_York','Etc/UTC'].map(t=>`<option ${C.timezone===t?'selected':''}>${t}</option>`).join('')}</select></div></div>`+
 (C.mode==='online'?`<div class="notice info"><strong>AUTO-UPDATING DISPLAY — NOT A GUARANTEE OF REAL TIME.</strong> The free widget lists U.S. stock feeds as delayed. Other symbols can be restricted or unavailable. Changes made inside its own symbol search do not change this app’s selected analysis ticker. No widget prices enter the quant engine.</div>`+(C.widgetConsent?`<section class="panel online-chart-panel"><iframe id="online-widget-frame" title="External TradingView chart for ${E(tv)}" src="/chart-widget.html?symbol=${encodeURIComponent(tv)}&interval=${frame}&timezone=${encodeURIComponent(C.timezone)}" sandbox="allow-scripts allow-popups allow-popups-to-escape-sandbox" referrerpolicy="no-referrer" loading="eager"></iframe></section>`:panel('Enable the free external chart','No subscription or API key required for supported symbols',`<div class="panel-body"><p>Enabling this loads TradingView’s widget, which receives your IP address, chosen symbol and embedding-page information. Your private database, notes and API keys are not sent.</p>${button('Enable online chart for this session','chart-consent','primary')}<p class="form-help">The chart runs in a separate sandbox. Symbols unavailable in free widgets can be opened using the direct link above. Local data stays usable when the embed is blocked.</p></div>`)):'')+
 panel('Local data & refresh','This feeds the calculations below, independently of the online display',`<div class="panel-body"><div class="feed-controls"><div><label for="chart-provider">DATA SOURCE</label><select id="chart-provider">${!['yahoo','alpaca-iex','webull-sandbox'].includes(C.provider)?`<option value="${E(C.provider)}" selected disabled>Saved ${E(C.provider)} observations · select an online source to fetch</option>`:''}<option value="yahoo" ${C.provider==='yahoo'?'selected':''}>Yahoo · free, no account · delay unverified</option><option value="alpaca-iex" ${C.provider==='alpaca-iex'?'selected':''}>Alpaca IEX · free keys · single exchange</option><option value="webull-sandbox" ${C.provider==='webull-sandbox'?'selected':''}>Webull sandbox · exact CME contract · M5 only</option></select></div><div><label for="chart-refresh">POLLING</label><select id="chart-refresh">${[[0,'Off'],...(C.provider==='alpaca-iex'?[[15,'Every 15 seconds']]:[]),[60,'Every 60 seconds'],[300,'Every 5 minutes']].map(([v,t])=>`<option value="${v}" ${C.auto===v?'selected':''}>${t}</option>`).join('')}</select></div>${button('Fetch data now ↻','chart-fetch','primary')}<span id="chart-refresh-status" class="subtle"></span></div><div id="chart-feed-message" class="form-help"></div>${C.provider==='alpaca-iex'?`<div class="notice info wide-space"><strong>${S.status.alpacaConfigured?'LOCAL IEX KEYS CONFIGURED':'OPTIONAL IEX KEYS NOT CONFIGURED'}</strong> · ${E(C.stream?.status||S.status.stream?.status||'OFF')}. ${button('Start event stream','chart-stream-start','small')}${button('Stop stream','chart-stream-stop','small')}<br>Upstream is a genuine Alpaca IEX WebSocket for eligible U.S. stocks/ETFs; the browser reads its bounded local relay. IEX is one exchange, not SIP/NBBO, SPX, options or CME. It stops when this view becomes unused.</div>`:''}${available.length?`<div class="row wide-space"><label for="chart-saved">Or use a saved ${E(C.symbol)} snapshot</label><select id="chart-saved"><option value="">Choose explicitly…</option>${available.map(s=>`<option value="${s.id}">${E(s.dataKind)} · ${s.barMinutes}m · ${E(dt(s.spotAsOf))}</option>`).join('')}</select></div>`:''}</div>`)+
 `<div id="chart-data-view" class="wide-space">${chartDataHTML()}</div>`;
}
async function prepareCharts(){if(!C.initialized){C.info=await api('/api/chart/resolve?symbol='+encodeURIComponent(ChartTools.inputSymbol(C.symbol)));C.symbol=C.info.symbol;C.initialized=true;}}
function updateChartStatus(){
 const e=$('#chart-refresh-status');if(e)e.textContent=C.busy?'Requesting…':!navigator.onLine?'Offline · paused':document.hidden?'Hidden tab · paused':C.auto?(C.nextAt?'Next check in '+Math.max(0,Math.ceil((C.nextAt-Date.now())/1000))+'s':'Refresh enabled'):'Manual mode';
 const m=$('#chart-feed-message');if(m){m.textContent=C.error?'Fetch failed: '+C.error+' Previous same-symbol observations retained.':C.lastSuccess?'Last successful fetch: '+dt(C.lastSuccess)+'. '+C.quoteMessage:'No automatic requests on startup. Polling pauses when this tab is hidden or offline; failures back off. Snapshots are saved only when you click Save.';m.classList.toggle('feed-error',Boolean(C.error));}
 $$('[data-chart-age]').forEach(e=>e.textContent=ChartTools.ageText(ChartTools.quality(C.snapshot).age));
}
function updateChartData(){if(S.page!=='charts')return;const target=$('#chart-data-view');if(target){charts.delete('selected-price-chart');target.innerHTML=chartDataHTML();requestAnimationFrame(drawCharts);}updateChartStatus();}
function stopChartTimer(){clearTimeout(C.timer);C.timer=null;C.nextAt=null;}
function scheduleChartRefresh(){stopChartTimer();if(!C.auto||S.page!=='charts'||document.hidden||!navigator.onLine)return;const delay=ChartTools.nextDelay(C.auto,C.failures);C.nextAt=Date.now()+delay*1000;C.timer=setTimeout(()=>refreshChart(false),delay*1000);updateChartStatus();}
async function selectChartSymbol(raw){const value=ChartTools.inputSymbol(raw);C.generation++;stopChartTimer();const generation=C.generation,info=await api('/api/chart/resolve?symbol='+encodeURIComponent(value));if(generation!==C.generation)return;C.info=info;C.symbol=info.symbol;C.snapshot=null;C.error='';C.failures=0;C.lastSuccess=null;C.quoteMessage='';C.recent=[C.symbol,...C.recent.filter(s=>s!==C.symbol)].slice(0,12);if(C.stream&&C.stream.status!=='OFF'){C.stream=info.alpaca?await api('/api/stream/start',{symbols:[info.symbol],clientId:C.streamClient}):await api('/api/stream/stop',{clientId:C.streamClient});C.streamClient=C.stream.clientId||null;C.streamSequence=0;}saveChartPrefs();if(S.page!=='charts'){location.hash='charts';}else render();scheduleChartRefresh();}

function stopStreamRelay(){clearTimeout(C.streamTimer);C.streamTimer=null;}
async function pollStream(){
 stopStreamRelay();if(S.page!=='charts'||document.hidden)return;
 try{const r=await api('/api/stream/events?since='+C.streamSequence+'&clientId='+encodeURIComponent(C.streamClient||''));C.stream=r.status;for(const event of r.events){C.streamSequence=Math.max(C.streamSequence,event.sequence);if(event.symbol===C.info?.alpaca&&event.type==='t'&&Number.isFinite(event.price)&&event.sourceAt&&C.snapshot){C.snapshot={...C.snapshot,spot:event.price,spotAsOf:event.sourceAt,streamReceiveAsOf:event.receivedAt,latencyClass:'STREAMING_IEX',feed:'alpaca-iex'};C.quoteMessage='IEX stream trade observed '+dt(event.sourceAt)+(event.late?' · late/out of order':'');}if(event.correction)C.quoteMessage='Provider correction/cancel event received; completed-bar decisions were not rewritten.';}if(r.gap)C.error='Local stream queue gap detected; refresh history before using completed bars.';updateChartData();}
 catch(e){C.error=e.message;updateChartStatus();}
 if(C.stream?.status!=='OFF')C.streamTimer=setTimeout(pollStream,1500);
}
async function refreshChart(manual=true){
 if(C.busy){if(manual)notify('A data request is already running.');scheduleChartRefresh();return;}
 if(!navigator.onLine){C.error='Browser is offline';updateChartStatus();return;}
 if(!manual&&(document.hidden||S.page!=='charts'))return;
 stopChartTimer();C.busy=true;C.lastAttempt=new Date().toISOString();updateChartStatus();
 const request={generation:C.generation,symbol:C.symbol,provider:C.provider,interval:C.interval};
 try{
  const r=await api('/api/chart/fetch',{symbol:request.symbol,interval:request.interval,provider:request.provider});
  if(!ChartTools.validResult(request,C,r.snapshot))return;
  const old=C.snapshot;C.snapshot=r.snapshot;C.lastSuccess=new Date().toISOString();C.failures=0;C.error='';C.quoteMessage=old&&old.spotAsOf===C.snapshot.spotAsOf?'Provider observation time has not advanced. A new request did not produce a new trade.':'Source observation: '+dt(C.snapshot.spotAsOf)+'.';
  updateChartData();if(manual)notify(C.symbol+' observations received. Check source time and market coverage.');
 }catch(e){if(request.generation===C.generation){C.error=e.message;C.failures++;updateChartStatus();if(manual)notify(e.message,true);}}
 finally{C.busy=false;updateChartStatus();scheduleChartRefresh();}
}
async function chartAction(action,el){
 if(action==='chart-symbol')return selectChartSymbol(el.dataset.symbol);
 if(action==='chart-fetch')return refreshChart(true);
 if(action==='chart-favorite'){const set=new Set(S.prefs.favorites||[]);set.has(C.symbol)?set.delete(C.symbol):set.add(C.symbol);S.prefs=await api('/api/settings',{...S.prefs,favorites:[...set]});render();return;}
 if(action==='chart-stream-start'){if(C.provider!=='alpaca-iex')throw Error('Select Alpaca IEX before starting its event stream');C.stream=await api('/api/stream/start',{symbols:[C.symbol],clientId:C.streamClient});C.streamClient=C.stream.clientId;C.streamSequence=0;pollStream();render();return;}
 if(action==='chart-stream-stop'){C.stream=await api('/api/stream/stop',{clientId:C.streamClient});C.streamClient=null;stopStreamRelay();render();return;}
 if(action==='chart-online'||action==='chart-local'){C.mode=action==='chart-online'?'online':'local';render();return;}
 if(action==='chart-consent'){C.widgetConsent=true;render();return;}
 if(action==='chart-export'){if(!C.snapshot)throw Error('Fetch or select a dataset first');return downloadJSON(C.snapshot,C.symbol+'-research-snapshot.json');}
 if(action==='chart-zoom-in'||action==='chart-zoom-out'){S.zoom=Math.max(30,Math.min(600,S.zoom+(action==='chart-zoom-in'?-30:30)));updateChartData();return;}
 if(action==='chart-pan-left'||action==='chart-pan-right'){S.pan=Math.max(0,S.pan+(action==='chart-pan-left'?Math.max(1,Math.floor(S.zoom/3)):-Math.max(1,Math.floor(S.zoom/3))));updateChartData();return;}
 if(action==='chart-reset'){S.zoom=90;S.pan=0;updateChartData();return;}
 if(action==='chart-analyse'||action==='chart-note'){
  if(!C.snapshot)throw Error('No local snapshot loaded');const r=await api('/api/import',{snapshot:C.snapshot});await refreshStatus();
  if(action==='chart-analyse'){await loadSnapshot(r.id);S.frame=C.snapshot.barMinutes;location.hash='overview';}
  else{await api('/api/notes',{symbol:C.symbol,snapshotId:r.id,category:'observation',text:`Research observation only: ${C.symbol} ${C.snapshot.spot} ${C.snapshot.currency||''}, observed ${C.snapshot.spotAsOf}. Source: ${C.snapshot.source}. No broker order or fill. SPX GEX is separate.`});notify('Observation saved with its source snapshot.');}
 }
}
function downloadJSON(value,name){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopChartTimer();stopStreamRelay();if(C.streamClient)api('/api/stream/stop',{clientId:C.streamClient}).then(s=>{C.stream=s;C.streamClient=null;}).catch(()=>{});}else scheduleChartRefresh();updateChartStatus();});
window.addEventListener('offline',()=>{stopChartTimer();updateChartStatus();});window.addEventListener('online',()=>{scheduleChartRefresh();updateChartStatus();});
setInterval(()=>{if(S.page==='charts')updateChartStatus();},1000);

// A separate SPX chain state prevents any stock-chart or feed refresh from
// changing the gamma underlying or relabeling SPY data as SPX.
async function prepareSPX(){
 const id=S.gexId||localStorage.getItem('hub.spx.snapshot');
 const chosen=S.snapshots.find(x=>x.id===id&&x.symbol==='SPX'&&x.optionCount>0)||S.snapshots.find(x=>x.symbol==='SPX'&&x.optionCount>0&&x.dataKind!=='synthetic');
 if(chosen&&S.gexId!==chosen.id)await loadSPX(chosen.id);
}
async function loadSPX(id){const s=S.cache.get(id)||await api('/api/snapshot?id='+encodeURIComponent(id));if(!ChartTools.isSPX(s))throw Error('Only native SPX chain snapshots can enter this GEX workspace.');S.gexScenario=null;S.gexPrice=null;S.gexSnapshot=s;S.gexId=id;S.cache.set(id,s);localStorage.setItem('hub.spx.snapshot',id);}
function spxDatasetBar(){const s=S.gexSnapshot,items=S.snapshots.filter(d=>d.symbol==='SPX'&&d.optionCount>0);return `<div class="dataset-bar"><label for="spx-dataset">SPX CHAIN ONLY</label><select id="spx-dataset"><option value="">Choose a native SPX chain…</option>${items.map(d=>`<option value="${d.id}" ${d.id===S.gexId?'selected':''}>${E(d.title)} · ${E(d.dataKind)} · ${E(dt(d.asOf))}</option>`).join('')}</select>${s?`<span class="snapshot-date">SPX ${num(s.spot)} · OBSERVED ${E(dt(s.spotAsOf))}</span>`:''}${button('Export GEX calculation','spx-export','small')}</div>`+(s?`<div class="notice ${s.dataKind==='synthetic'?'':'info'}"><strong>${s.dataKind==='synthetic'?'SYNTHETIC SPX WALKTHROUGH':'NATIVE SPX / SPXW · USER-IMPORTED'}</strong> · ${E(s.source)}. Chart symbol <strong>${E(C.symbol)}</strong> is independent. GEX is computed at the chain capture time ${E(dt(s.asOf))}, not at the current clock time.</div>`:'');}
function spxImportHTML(){const p=S.gexPreview;return panel('Load your native SPX option chain','SPX/SPXW only · preview every row · no ETF proxy',`<div class="panel-body"><form id="spx-import-form"><div class="form-grid"><div class="span"><label for="spx-file">SPX snapshot JSON, normalized CSV, or manually exported Cboe paired CSV</label><input id="spx-file" type="file" name="file" accept=".csv,.json" required></div><div>${inputField('SPX reference level (CSV)','spot','','min="0.001"').replace(/^<div>|<\/div>$/g,'')}</div><div><label for="spx-source">Source / broker export name (CSV)</label><input id="spx-source" name="source" placeholder="Manually exported Cboe SPX table"></div><div><label for="spx-asof">Chain capture time (CSV, ISO + timezone)</label><input id="spx-asof" name="asOf" placeholder="2026-09-08T14:30:00Z"></div><div><label for="spx-spotasof">SPX reference observation time (CSV)</label><input id="spx-spotasof" name="spotAsOf" placeholder="2026-09-08T14:29:45Z"></div><div class="span"><label for="spx-oi">Open-interest reference date / provider note (CSV)</label><input id="spx-oi" name="oiAsOf" placeholder="Provider OI date, or leave blank as unknown"></div></div><label class="check"><input name="synthetic" type="checkbox">Synthetic / example data — never label it as actual market data</label><button class="button primary" type="submit">Preview, validate & save →</button></form>${p?`<div class="notice ${p.rejected?'error':'info'} wide-space"><strong>${E(p.status)}</strong> · ${p.accepted} accepted · ${p.rejected} rejected · ${p.lifecycleAmbiguous} lifecycle ambiguities. ${p.rejected?button('Download rejection CSV ↓','spx-preview-download','small'):''}</div>`:''}<p class="form-help">Normalized CSV requires underlying, native root, type, strike, exact expiry, multiplier=100 and OI (blank remains unknown). Lifecycle qualification requires settlementType, lastTradingAt, payoffFixingAt/settlementAt and expiryVerified=true. Date-only Cboe exports remain unqualified until repaired; their supplied-gamma arithmetic is shown separately. Rejected rows are never partly saved.</p><p><a href="/api/spx/sandbox-export">Download the included 368-contract Webull sandbox chain ↓</a> · <a href="https://www.cboe.com/delayed_quotes/spx/quote_table/" target="_blank" rel="noopener noreferrer">Open official Cboe delayed SPX chain ↗</a> · <a href="/api/template?kind=spx-options">Synthetic normalized SPX CSV template ↓</a> · <a href="/api/template?kind=spx">Complete synthetic SPX JSON example ↓</a></p><div class="notice info">The included Webull export is partial, sandbox and lifecycle-unqualified. For Cboe, enter SPX and download through its page manually; this app does not scrape or automatically download it. Missing or incomplete native data stays unavailable/partial.</div></div>`);}
function emptySPX(){return pageHeading('SPX ONLY / INDEPENDENT OF YOUR STOCK CHART','SPX gamma exposure','Changing the chart symbol never changes this workspace’s underlying.',button('Load synthetic SPX walkthrough','load-spx-demo'))+spxDatasetBar()+`<div class="notice info"><strong>NO NATIVE SPX CHAIN LOADED — GEX IS UNAVAILABLE, NOT ZERO.</strong> SPY/QQQ options are not converted into SPX. All stock charts remain available in the Charts workspace.</div>`+spxImportHTML();}
async function importSPX(form){const f=new FormData(form),file=f.get('file');if(!file?.size||file.size>15000000)throw Error('Choose an SPX CSV/JSON file smaller than 15 MB');const text=await file.text();let body;
 if(file.name.toLowerCase().endsWith('.csv'))body={format:'csv',text,originalName:file.name,metadata:{spot:Number(f.get('spot')),asOf:f.get('asOf'),spotAsOf:f.get('spotAsOf'),source:f.get('source'),oiAsOf:f.get('oiAsOf'),dataKind:f.has('synthetic')?'synthetic':'imported'}};
 else{const snapshot=JSON.parse(text);if(f.has('synthetic'))snapshot.dataKind='synthetic';body={snapshot,rawText:text,originalName:file.name};}
 S.gexPreview=await api('/api/gex/preview',body);if(S.gexPreview.rejected||!S.gexPreview.accepted){render();notify('SPX preview found rejected rows. Download the report, correct the source, and retry.',true);return;}const r=await api('/api/gex/import',body);await refreshStatus();await loadSPX(r.id);render();notify('SPX chain saved separately with raw-file hash. Your chart and stock dataset were not changed.');
}
async function spxAction(action){
 if(action==='load-spx-demo'){const fixture=await api('/api/template?kind=spx');const r=await api('/api/gex/import',{snapshot:fixture});await refreshStatus();await loadSPX(r.id);render();notify('Synthetic SPX example selected explicitly. It is not current market data.');}
 if(action==='spx-export'){if(!S.gexSnapshot)throw Error('Load a native SPX chain first');const s=S.gexSnapshot,g=HR.gamma(s,{convention:S.gexConvention,maxDays:S.gexDays});downloadJSON({schema:'trading-hub.gex-export.v2',symbol:'SPX',snapshotId:S.gexId,model:{version:GQ.VERSION,rate:s.rate,dividend:s.dividend,curve:'Sticky-strike IV Black–Scholes–Merton, ±8% spot scan'},chainComplete:s.chainComplete,qualificationStatus:g.qualificationStatus,independentlyVerified:g.independentlyVerified,coverage:{qualifiedRows:g.rows?.length,importedRowsInHorizon:g.importedInHorizon,percent:g.coverage,meaning:g.coverageMeaning,missingOI:g.missingOI,lifecycleExcluded:g.lifecycleExcluded,unqualifiedArithmeticRows:g.unqualifiedRows.length},chainAsOf:s.asOf,spotAsOf:s.spotAsOf,spot:s.spot,source:s.source,sourceHash:s.sourceHash||null,dataKind:s.dataKind,oiAsOf:s.oiAsOf,convention:S.gexConvention,maxDays:S.gexDays,units:'USD delta-notional change / 1% SPX move',assumedNet:g.net,gross:g.gross,grossCalls:g.grossCalls,grossPuts:g.grossPuts,unqualifiedSuppliedGammaArithmetic:{net:g.unqualifiedNet,gross:g.unqualifiedGross},callConcentration:g.callWall,putConcentration:g.putWall,curveStatus:g.curveStatus,testedSpotRange:g.testedSpotRange,crossings:g.flips,strikes:g.strikes,curve:g.curve,limitations:['Dealer holdings are not observed; signs are assumptions.','Coverage is of imported rows, not the complete market.','Partial chain and missing IV may produce an incomplete sensitivity curve.','Not a trading signal or profit estimate.'],executionEligible:false},'SPX-GEX-research.json');}
 if(action==='spx-preview-download'){if(!S.gexPreview)throw Error('Preview an SPX import first');const quote=v=>{let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';},rows=[['row','contract','reason'],...S.gexPreview.rejections.map(r=>[r.row,r.contract,r.reason])],blob=new Blob([rows.map(row=>row.map(quote).join(',')).join('\r\n')+'\r\n'],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='SPX-import-rejection-report.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
}
