'use strict';
const alertSaved=(()=>{try{const s=JSON.parse(localStorage.getItem('hub.alerts.v1')||'{}');return s&&typeof s==='object'?s:{};}catch{return {};}})();
const A={enabled:alertSaved.enabled!==false,desktop:alertSaved.desktop===true,tracks:Object.fromEntries(Object.entries(alertSaved.tracks&&typeof alertSaved.tracks==='object'?alertSaved.tracks:{}).slice(-32)),events:Array.isArray(alertSaved.events)?alertSaved.events.slice(-100):[],seen:new Set(),message:'Dashboard alerts use future completed observations; opening a page does not replay historical purchase signals.'};
function saveAlerts(){try{localStorage.setItem('hub.alerts.v1',JSON.stringify({enabled:A.enabled,desktop:A.desktop,tracks:A.tracks,events:A.events.slice(-100)}));}catch{A.message='Browser storage unavailable. Alerts remain in this session; save important reviews to the journal.';}}
function monitorBackgroundAllowed(){return A.desktop&&typeof Notification!=='undefined'&&Notification.permission==='granted';}
function resetAlertObservation(){A.seen.clear();}
function alertPanel(){const permission=typeof Notification==='undefined'?'unsupported':Notification.permission;return panel('Setup alerts','Breakout → later completed retest → review; never an automatic purchase',`<div class="panel-body"><div class="row">${button(A.enabled?'Dashboard alerts ON':'Dashboard alerts OFF','alert-toggle',A.enabled?'primary':'')}${button(A.desktop?'Disable browser notifications':'Enable browser notifications','alert-desktop')}${button('Send test notification','alert-test','small')}${button('Mark alerts read','alert-read','small')}</div><p>${E(A.message)}</p><p>Browser permission: <strong>${E(permission)}</strong>. Background monitoring ${monitorBackgroundAllowed()?'is enabled for this started session':'is off'}. With notifications enabled, monitoring can continue across Hub views or another tab. The server and browser must stay open; sleep or browser throttling can delay checks. No service worker, message service or schedule is installed.</p><p>Technical confirmation still leaves current bid/ask, option quote/contract, strategy and account gates open. Options cannot be purchased through this Hub.</p><div role="log" aria-live="polite">${A.events.slice(-8).reverse().map(e=>`<div class="audit-item"><time>${E(dt(e.knownAt))}</time><div><h3>${E(e.symbol)} ${e.direction==='bullish'?'LONG':e.direction==='bearish'?'SHORT':''} · ${E(e.type.replaceAll('_',' '))}</h3><p>${E(e.reason)}</p>${e.frozen?`<p>Frozen entry ${num(e.frozen.entry)} · stop ${num(e.frozen.stop)} · no chase ${num(e.frozen.noChase)}. Source ${E(dt(e.referenceAsOf))}.</p>`:''}<small>${E(e.audit||'Session audit')} · no order</small></div></div>`).join('')||'<p>No new confirmed setup observed. The first scan establishes a baseline.</p>'}</div></div>`);}
function updateAlertBanner(){const el=document.getElementById('setup-alert-banner');if(!el)return;const latest=[...A.events].reverse().find(e=>!e.read&&['SETUP_READY_FOR_REVIEW','CORRECTION_REVIEW_REQUIRED','FLUSH_WATCH','TRIM_WATCH','RISK_WATCH_WITHDRAWN'].includes(e.type));const active=latest&&M.enabled&&(latest.type!=='SETUP_READY_FOR_REVIEW'||Object.values(A.tracks).some(t=>t.ready?.id===latest.id));el.innerHTML=latest?`<div class="notice info" role="status"><strong>${E(latest.symbol)} · ${E(latest.type.replaceAll('_',' '))}</strong> · ${E(dt(latest.knownAt))} · ${active?'Current monitor transition; recheck price and gates.':'DATED ALERT — confirmation is not current.'} ${E(latest.reason)} <a href="#home">Review trade screen</a></div>`:'';}
function sendDesktopAlert(e){if(!A.desktop||typeof Notification==='undefined'||Notification.permission!=='granted')return;try{const special=['FLUSH_WATCH','TRIM_WATCH'].includes(e.type),body=e.test?'Browser alerts are available. This is a test, not a trading signal.':e.type==='SETUP_READY_FOR_REVIEW'?'Later retest confirmed. Check current quotes, option chain and risk before any paper order.':special?e.reason:'Confirmation or risk watch changed: '+e.reason;const n=new Notification(e.test?'Hub notification test':`${e.symbol} · ${e.direction==='bullish'?'LONG':e.direction==='bearish'?'SHORT':'RISK'} · research review`,{body,tag:e.id,requireInteraction:false});n.onclick=()=>{window.focus();location.hash='home';n.close();};}catch{A.message='Browser notification could not be displayed. Dashboard alerts remain available; check browser/OS notification permission.';}}
async function auditSetupAlert(e,s){try{const saved=await api('/api/import',{snapshot:s});await api('/api/notes',{symbol:s.symbol,snapshotId:saved.id,dataKind:s.dataKind,category:'research',text:JSON.stringify({...e,schema:'hub.setup-alert.v1',ruleVersion:'rolling20-alert-review-1',orderSubmitted:false})});e.audit='Saved with source bars in journal';}catch{e.audit='Journal save failed; retained in browser alert history';}saveAlerts();updateAlertBanner();}
function alertTrackKey(s,interval){return [s.instrumentId,s.feed,interval,s.sessionModel,s.adjustment].join('|');}
function processMonitorAlerts(){
 if(!A.enabled||!M.enabled)return;const active=new Set();
 for(const row of monitorRows()){
  if(!row.snapshot)continue;const s=monitorSnapshot(row),key=alertTrackKey(s,row.interval);active.add(key);
  const r=MonitorTools.review(s,{cost:M.cost,session:S.status.health.sessions.usEquities,eventFreeze:S.prefs.eventFreeze,brief:M.brief,feedError:row.error}),previous=A.tracks[key];
  const result=AlertRules.advance(previous,{review:r,bars:HR.stats(s,r.frame).series,dataHash:row.hash,resuming:!A.seen.has(key)}),card=MonitorTools.card(r,result.track,true),range=MarketContext.expectedRange(typeof H==='undefined'?{}:H.expected),risk=MarketContext.riskState({...card,snapshot:s},range);
  const watched=['FLUSH_WATCH','TRIM_WATCH'],prior=previous?.riskState;result.track.riskState=risk.code;
  if(prior&&prior!==risk.code&&(watched.includes(risk.code)||watched.includes(prior))){const type=watched.includes(risk.code)?risk.code:'RISK_WATCH_WITHDRAWN',p=card.scenario;result.events.push({id:[r.instrument,r.feed,r.frame,type,p?.direction||'',s.spotAsOf].join('|'),type,symbol:r.symbol,instrument:r.instrument,feed:r.feed,horizon:r.horizon,direction:p?.direction||null,knownAt:new Date().toISOString(),barStart:r.signalBarStart,referenceAsOf:r.sourceObservedAt,dataHash:row.hash,frozen:p?{entry:p.entry,stop:p.stop,t1:p.t1,t2:p.t2,noChase:p.noChase,boundary:p.boundary}:null,reason:type==='RISK_WATCH_WITHDRAWN'?'Prior '+prior.replaceAll('_',' ').toLowerCase()+' conditions no longer agree.':risk.reason,decisionBasis:r.decisionBasis,qualification:'RESEARCH_ONLY; KX BLOCKED',quantity:null,executable:false});}
  A.tracks[key]=result.track;A.seen.add(key);
  for(const e of result.events){if(A.events.some(old=>old.id===e.id))continue;A.events.push(e);A.events=A.events.slice(-100);if(['SETUP_READY_FOR_REVIEW','CORRECTION_REVIEW_REQUIRED','CONFIRMATION_WITHDRAWN','DATA_GATE','MONITOR_GAP','FLUSH_WATCH','TRIM_WATCH','RISK_WATCH_WITHDRAWN'].includes(e.type))sendDesktopAlert(e);auditSetupAlert(e,s);}
 }
 for(const key of Object.keys(A.tracks))if(!active.has(key))delete A.tracks[key];saveAlerts();updateAlertBanner();
}
async function alertAction(action){
 if(action==='alert-toggle'){A.enabled=!A.enabled;A.tracks={};resetAlertObservation();A.message=A.enabled?'Alerts enabled. Next scan establishes a baseline.':'Setup alerts disabled.';}
 if(action==='alert-read')A.events.forEach(e=>e.read=true);
 if(action==='alert-desktop'){
  if(A.desktop){A.desktop=false;A.message='Browser notifications disabled. Hidden-page monitoring is disabled.';if(document.hidden||!monitorViewActive())stopMonitor(A.message);}
  else if(typeof Notification==='undefined')A.message='This browser does not support desktop notifications. Use dashboard alerts.';
  else{const permission=await Notification.requestPermission();A.desktop=permission==='granted';A.message=A.desktop?'Browser notifications enabled. Start monitoring to watch for future confirmations.':'Notification permission was not granted. Dashboard alerts work; allow this loopback site in browser settings to enable desktop alerts.';}
 }
 if(action==='alert-test'){if(!monitorBackgroundAllowed())A.message='Enable browser notifications and allow permission before sending a test.';else{sendDesktopAlert({test:true,id:'hub-explicit-notification-test'});A.message='Test notification requested. Its appearance also depends on OS notification settings.';}}
 saveAlerts();updateAlertBanner();render();
}
